version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"  # Le serveur Artisan écoutera sur ce port
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-csmlrg08fa8c73a8eu2g-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: oxygen_laravel
      DB_USERNAME: oxygen_laravel_user
      DB_PASSWORD: nLJiiAzGoIKUp6XNsnDLmwK19cRj1q2E

  postgres:  # Service PostgreSQL
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: oxygen_laravel
      POSTGRES_USER: oxygen_laravel_user
      POSTGRES_PASSWORD: nLJiiAzGoIKUp6XNsnDLmwK19cRj1q2E
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:  # Volume persistant pour les données PostgreSQL